// Observaciones predefinidas para cotizaciones de CETOX LAB
// Lista mantenida por el equipo técnico — se selecciona desde el formulario
// de nueva cotización y se inserta en el campo "observaciones".

export const OBSERVACIONES_PREDEFINIDAS: string[] = [
  'Enviar las muestras en cadena de frío.',
  'Enviar las muestras en cadena de frío y sin cámara de aire.',
  'Se requiere que el paciente se encuentre en ayunas para la toma de muestra.',
  'Los ensayos de Irritación Dérmica y Ocular dependerán de los resultados de la prueba de pH/efecto tampón.',
  'No han sido solicitados los ensayos histopatológicos, ya que, los resultados serán presentados en Perú.',
  'Se le indicará al cliente a través de una carta o documento con la sustentación técnica de la no realización del ensayo de Toxicidad Inhalatoria.',
  'El cliente se encargará de la movilidad del personal profesional del CETOX para la toma de muestra (ida y vuelta), previa coordinación de fecha y hora.',
  'Se le ha otorgado un descuento especial por el número de muestras y/o ensayos, el cual, se mantendrá siempre y cuando ingrese el mismo o mayor número de muestras.',
  'Se requiere la entrega de los informes de ensayo originales para la modificación solicitada.',
  'Se realiza el pH/efecto tampón para indicar si se realizará los ensayos de Irritación Dérmica y/u Irritación Ocular, fundamentado por la OECD. En caso de no ser necesarios dichos ensayos se le brindará una carta aclaratoria, siendo aceptada en casos similares por la autoridad competente. En caso que al realizar la prueba de pH/efecto tampón nos indique que sí se debe realizar estos ensayos, se le brindará en la brevedad posible la información respectiva con la cotización de estos 2 ensayos.',
  'El envío de resultados sería a través del Courier de su preferencia vía Collect.',
  'Se requiere la hoja de seguridad de cada producto.',
  'Las cepas, dosis, tiempos de contacto y/o carga microbiana serán indicados al momento de ingresar la muestra. Si varía el número de cepas y/ dosis de lo cotizado, el costo también variará.',
  'Para el análisis de mercurio en agua, enviar la muestra preservada a pH < 2 (usualmente 1.5 mL de HNO3 conc/L de muestra) y conservadas por encima de 0ºC y ≤ 6ºC.',
  'Para el ensayo de efectos de reproducción y tasa de crecimiento de peces, se requiere saber el NOEC del ensayo de Toxicidad crónica en peces (de la misma especie solicitada), en caso de no tenerla podemos ofrecerle realizar dicho ensayo.',
  'Para el ensayo de Ritmo de crecimiento y/o Tasa de reproducción en Daphnia magna, se requiere saber la CE50 del ensayo de Toxicidad aguda en Daphnia y el NOEC y LOEC del ensayo de Toxicidad Crónica en Daphnia, en caso de no tenerla podemos ofrecerle realizar dichos ensayos.',
  'Para el ensayo de Toxicidad crónica para Daphnia magna, se requiere saber la CL50 aguda en Daphnia, en caso de no tenerla podemos ofrecerle realizar dicho ensayo.',
  'Se ha cotizado el ensayo de Toxicidad Dérmica aguda en RATAS (especie solicitada en Chile para este ensayo), si los Informes de ensayo fueran presentados en otros países se debería realizar en CONEJOS.',
  'Se ha cotizado la Toxicidad Dérmica aguda en CONEJOS, si los Informes de ensayo fueran presentados en Chile, las autoridades de dicho país solicitan realizar el ensayo de Toxicidad Dérmica en RATAS.',
  'Por el número de muestras y/o ensayos cotizados, el tiempo de entrega de resultados se indicará el día que ingresen las muestras.',
  'Para el ensayo de eficacia en insectos, el cliente deberá indicar la dosis de uso al momento de ingresar la muestra.',
  'El área técnica de CETOX confirmará si se puede realizar el ensayo de Toxicidad Inhalatoria en ratas al momento de recibir la muestra, ya que, por las características y/o naturaleza de la misma, no se podría ejecutar dicho ensayo, la cual, sería sustentada a través de una carta emitida por CETOX fundamentada por la OECD y/ Manual Técnico Andino.',
  'Observaciones:',
  'Se realiza el pH para indicar si se realizará los ensayos de Irritación Dérmica en conejos e Irritación Ocular en conejos, fundamentado por la OECD. En caso de no ser necesarios dichos ensayos se le brindará una carta aclaratoria, siendo aceptada en casos similares por la autoridad competente. En caso que al realizar la prueba de pH/efecto tampón nos indique que si se debe realizar estos ensayos, se le brindará en la brevedad posible la información respectiva con la cotización de estos 2 ensayos.',
  'Para el ensayo de Efectos en la reproducción en aves (codorniz), se requiere saber la DL50 aguda en codorniz, en caso de no tenerla podemos ofrecerle realizar dicho ensayo.',
  'Para el ensayo de Toxicidad crónica para peces (trucha arco iris), se requiere saber la CL50 aguda en trucha, en caso de no tenerla podemos ofrecerle realizar dicho ensayo.',
  'Para el ensayo de Toxicidad crónica para Daphnia magna, se requiere saber la CL50 ó CE50 aguda en Daphnia, en caso de no tenerla podemos ofrecerle realizar dicho ensayo.',
  'Para Toxicidad Oral subcrónica a 28 días:',
  'Para el ensayo de Toxicidad Oral subcrónica a 28 días en ratas, se requiere saber la DL50 del ensayo de Toxicidad oral aguda en ratas, en caso de no tenerla podemos ofrecerle realizar dicho ensayo.',
  'Para Toxicidad subcrónica dermal a 21 ó 28 días (conejos)',
  'Para el ensayo de Toxicidad subcrónica dermal a 21 ó 28 días en conejos, se requiere saber la DL50 del ensayo de Toxicidad dérmica aguda en conejos, en caso de no tenerla podemos ofrecerle realizar dicho ensayo.',
  'Para Toxicidad subcrónica inhalatoria a 21 ó 28 días (ratas)',
  'Para el ensayo de Toxicidad subcrónica inhalatoria a 21 ó 28 días en ratas, se requiere saber la CL50 del ensayo de Toxicidad inhalatoria aguda en ratas, en caso de no tenerla podemos ofrecerle realizar dicho ensayo.',
  'Para Efectos en la reproducción en aves (codorniz)',
  'Para el ensayo de Efectos en la reproducción en aves (codorniz), se requiere saber la DL50 aguda en codorniz, en caso de no tenerla podemos ofrecerle realizar dicho ensayo.',
  'Para Efectos en la reproducción y tasa de crecimiento de peces (trucha)',
  'Para el ensayo de Efectos en la reproducción y tasa de crecimiento de peces (trucha arco iris), se requiere saber la CL50 aguda en trucha y el NOEC en trucha, en caso de no tenerlas podemos ofrecerles realizar dichos ensayos.',
]
