-- AlterTable
ALTER TABLE "CotizacionProveedor" ADD COLUMN "percepcion" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "OrdenCompra" ADD COLUMN "percepcion" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Factura" ADD COLUMN "percepcion" DOUBLE PRECISION NOT NULL DEFAULT 0;
